### ISSUE TITLE
About converting to .plan file format

### ISSUE THREAD

**Issue by hexisyztem** [espnet/espnet_onnx#108]
Will the .onnx model file converted by espnet_onnx have a control flow structure? Because when there is control flow in .onnx, there will be problems converting to .plan for tensorRT

**Comment by Masao-Someki** [comment]
I'm sorry, but I'm not entirely sure about the details. We're simply using the torch.onn.export function for model exportation. Therefore, if the ONNX file generated from this function includes control flow, then our model will also have them.

https://github.com/espnet/espnet_onnx/blob/5828178cbe1375f397e011c1851e0ea9a9aeff20/espnet_onnx/export/asr/export_asr.py#L246-L255

**Comment by hexisyztem** [comment]
OK, thanks
