### ISSUE TITLE
About TorchDynamo

### ISSUE THREAD

**Issue by hexisyztem** [espnet/espnet_onnx#110]
Have you considered using torchDynamo instead of tracing for exporting the ONNX model? You can refer to the document below.
https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html
https://pytorch.org/docs/stable/torch.compiler_deepdive.html

**Comment by Masao-Someki** [comment]
Thank you, @hexisyztem. We haven't discussed TorchDynamo before, but if it can speed up inference, we should consider supporting it. Unfortunately, I don't have enough time right now, but I can look into it in October.
