### ISSUE TITLE
Batch beam search output error and Transformer LM init cache issue

### ISSUE THREAD

**Issue by park-ing** [espnet/espnet_onnx#118]
Hello, 
I converted a model created with ESPnet to ONNX and conducted tests using your repo as a reference. 
However, I encountered the following two issues.

**1. Batch beam search.**
I discovered an issue with repeated token outputs in the CTC results and have been working to resolve it.
As a result, I found differences between the implementation in your batch_beam_search.py and ESPnet's batch_beam_search.py. 

Your code omits the log_softmax operation in the batch_init_state function. Is this the intended behavior?

Here, ESPNet
https://github.com/espnet/espnet/blob/b1046403ec7a20469594cb9f6ad3cbe58a7e6c81/espnet/nets/scorers/ctc.py#L96-L97
```
logp = self.ctc.log_softmax(x.unsqueeze(0))  # assuming batch_size = 1
xlen = torch.tensor([logp.size(1)])
```

And espnet_onnx
https://github.com/espnet/espnet_onnx/blob/647f3c69013833111c1a1aa51e80e240c9db7c0e/espnet_onnx/asr/scorer/ctc_prefix_scorer.py#L180-L181

I added log_softmax, and it works well.

**2. Transformer LM init.**
When exporting the Transformer LM to ONNX, the dummy input is initialized with the encoder's attention unit (e.g., 512).
https://github.com/espnet/espnet_onnx/blob/647f3c69013833111c1a1aa51e80e240c9db7c0e/espnet_onnx/export/asr/models/language_models/transformer.py#L73-L79

However, when loading the ONNX model for decoding, it is initialized with the vocab size, odim.
https://github.com/espnet/espnet_onnx/blob/647f3c69013833111c1a1aa51e80e240c9db7c0e/espnet_onnx/asr/model/lms/transformer_lm.py#L89-L94

I changed odim to the attention unit, and I confirmed that it works well.

**Comment by Masao-Someki** [comment]
Thank you, @park-ing, for your input.

1. **Batch Beam Search**  
   From my understanding, the `log_softmax` operation is already included in the export script. Could you please confirm whether the `log_softmax` is indeed part of the export process? If it is included, but we still need to compute the `log_softmax`, I will investigate this further.  
   https://github.com/espnet/espnet_onnx/blob/647f3c69013833111c1a1aa51e80e240c9db7c0e/espnet_onnx/export/asr/models/layers/ctc.py#L15-L16

2. **Transformer LM Initialization**  
   I understand this might be a bit confusing. The Transformer LM in ESPnet shares the same module as the Transformer Encoder. This is why the initialization tensor shape uses `encoder.encoders[0].size`, which is actually the input size of the Transformer LM.

   The `odim` value is initialized based on `config.odim`, which is defined in the export script:  
   https://github.com/espnet/espnet_onnx/blob/647f3c69013833111c1a1aa51e80e240c9db7c0e/espnet_onnx/export/asr/models/language_models/transformer.py#L112

   In your configuration, the `odim` should correspond to the size of the attention unit. However, if it is set to your vocabulary size, this could a bug. Please check your configuration.

**Comment by park-ing** [comment]
Thank you for your response!

1. I exported my ASR model based on espnet1 to ONNX by referring to this repo.
The `ctc.py` in espnet1 does not include the `log_softmax` operation. I appreciate your detailed explanation.

2. This issue also has arisen due to working with the espnet1-based model. After modifying the `odim`, it works well now. I appreciate your help.
