### ISSUE TITLE
A difference in accuracy between a onnx conformer model and a torch conformer model.

### ISSUE THREAD

**Issue by ken57** [espnet/espnet_onnx#38]
Sorry to bother you again.

I tested the conformer model of espnet_onnx by using CSJ corpus.
There was a difference in accuracy between a onnx conformer model and a torch conformer model.

I describe how I tested the conformer model of espnet_onnx by using CSJ corpus.
I downloaded the CSJ torch conformer model ( https://zenodo.org/record/4065140#.YsurAezP30o ), and converted it to the onnx model by using a script shown below.

```
from espnet2.bin.asr_inference import Speech2Text
from espnet_onnx.export import ASRModelExport

m = ASRModelExport()

m.set_export_config(max_seq_len=3000)
speech2text = Speech2Text.from_pretrained('asr_train_asr_conformer_raw_char_sp_valid.acc.ave.zip')
m.export(speech2text, 'kan-bayashi/csj_asr_train_asr_conformer_raw_char_sp_valid.acc.ave', quantize=False)
```

I modified ~/.cache/espnet_onnx/kan-bayashi/csj_asr_train_asr_conformer_raw_char_sp_valid.acc.ave/config.yaml as shown below.
```
weights:
  ctc: 0.3
  decoder: 0.7
  length_bonus: 0.0
  lm: 0.3
  ngram: 0.0
```
I transcribed CSJ eval sets with the onnx conformer model in the same manner as https://github.com/Masao-Someki/espnet_onnx/issues/36#issue-1295560021

I obtained results shown below.
```
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_asr_lm_lm_train_lm_jp_char_valid.loss.ave_asr_model_valid.acc.ave/eval1|1272|43897|95.0|3.3|1.7|1.2|6.2|56.3|
|decode_asr_lm_lm_train_lm_jp_char_valid.loss.ave_asr_model_valid.acc.ave/eval2|1292|43623|96.5|2.3|1.2|0.8|4.3|53.3|
|decode_asr_lm_lm_train_lm_jp_char_valid.loss.ave_asr_model_valid.acc.ave/eval3|1385|28225|96.0|2.6|1.4|1.0|5.0|38.1|
```

I transcribed CSJ eval sets with the torch conformer model( https://zenodo.org/record/4065140#.YsurAezP30o ).
I obtained a result shown below.
```
### CER

|dataset|Snt|Wrd|Corr|Sub|Del|Ins|Err|S.Err|
|---|---|---|---|---|---|---|---|---|
|decode_asr_lm_lm_train_lm_jp_char_valid.loss.ave_asr_model_valid.acc.ave/eval1|1272|43897|96.3|2.3|1.5|0.7|4.5|49.4|
|decode_asr_lm_lm_train_lm_jp_char_valid.loss.ave_asr_model_valid.acc.ave/eval2|1292|43623|97.2|1.7|1.0|0.5|3.3|47.6|
|decode_asr_lm_lm_train_lm_jp_char_valid.loss.ave_asr_model_valid.acc.ave/eval3|1385|28225|97.2|1.8|1.0|0.7|3.6|32.5|
```

Could you give me any hint to improve accuracy?
Thanks for your help.

**Comment by Masao-Someki** [comment]
Hi @ken57, thank you for reporting the issue.
Considering the transformer model worked nicely, I think there might be some inaccurate codes in conformed-related scripts...
Currently, I don't have much time to work on this, so is it okay to debug this weekend?

**Comment by ken57** [comment]
Of cause. 
Thank you for your kind support.

**Comment by Masao-Someki** [comment]
Hi @ken57, after some investigation, I found that there seems to be a problem with the legacy version of multi-head attention with relative positional encoding. I've added a parity check for the exported model, but the difference between the original model and the exported one is pretty larger than the latest version of RelPosAttention. I think this difference causes the accuracy loss.
Currently, I'm working on the optimization script for Conformer, so I will fix this bug about legacy RelPosAttention in that PR!

**Comment by ken57** [comment]
Thank you for your kind notice.
I'll be waiting for the updates.

**Comment by pengaoao** [comment]
I Met the same problem, I export the model https://zenodo.org/record/4105763#.X40xe2j7QUE, I test the onnx cer is 11.7,  while the torch infer cer is 4.7

**Comment by Masao-Someki** [comment]
@ken57 @pengaoao 
Hi, Sorry for the late reply. 
As tested in the ci, we could ensure that MSE between the outputs of torch and onnx is less than 1e-10, and the estimated token is the same, so I think we could fix all issues related to the accuracy problem. Would you try your accuracy test with the latest version?

**Comment by ken57** [comment]
I was able to confirm an accuracy of generated ONNX model is as same as the original model.
This issue is resolved in the latest version.
Thank you for your kind support.
