### ISSUE TITLE
AttributeError: 'ContextualBlockXformerEncoder' object has no attribute 'get_frontend_config'

### ISSUE THREAD

**Issue by espnetUser** [espnet/espnet_onnx#57]
Hi, 

First, thanks a lot for your work on onnx conversion of espnet models!

I am trying to convert a streaming Conformer-Transformer model (encoder: contextual_block_conformer, decoder: transformer) from espnet2 to onnx format.
It is not a pretrained espnet_zoo model but I trained it on my own data.

My call is this:
```
import sys
from espnet_onnx.export import ASRModelExport

model="./asr_train_asr_streaming_conformer7_n_fft256_hop_length128_conv2d_n_mels40_medium_raw_de_bpe5000_sp_valid.acc.ave.zip"
tag_name="streaming_conformer-transformer"

m = ASRModelExport()
m.export_from_zip(
  model,
  tag_name,
  optimize=True,
  quantize=True
)
```

I am getting the following error:
```
  m.export_from_zip(
  File "/home/espnetUser/scm/external/espnet_onnx/espnet_onnx/export/asr/export_asr.py", line 191, in export_from_zip
    self.export(model, tag_name, quantize, optimize)
  File "/home/espnetUser/scm/external/espnet_onnx/espnet_onnx/export/asr/export_asr.py", line 92, in export
    model_config.update(encoder=enc_model.get_model_config(
  File "/home/espnetUser/scm/external/espnet_onnx/espnet_onnx/export/asr/models/encoders/contextual_block_xformer.py", line 188, in get_model_config
    frontend=self.get_frontend_config(asr_model.frontend),
  File "/home/espnetUser/scm/external/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ContextualBlockXformerEncoder' object has no attribute 'get_frontend_config'
```
I also tried converting two pretrained espnet models:

Non-streaming model:
```
kamo-naoyuki/librispeech_asr_train_asr_conformer6_n_fft512_hop_length256_raw_en_bpe5000_scheduler_confwarmup_steps40000_optim_conflr0.0025_sp_valid.acc.ave.zip
```

This worked fine for me.

Streaming model:
```
Emiru_Tsunoo/aishell_asr_train_asr_streaming_transformer_raw_zh_char_sp_valid.acc.ave.zip
```
Here I am getting the same ```AttributeError: 'ContextualBlockXformerEncoder' object has no attribute 'get_frontend_config'``` error as for my own streaming model.

Any suggestions what is going wrong? Do I need a special espnet/python etc. version for the streaming models?

Thanks!

**Comment by Masao-Someki** [comment]
@espnetUser Sorry for the late replay, I think we need to remove `self` from [this line](https://github.com/espnet/espnet_onnx/blob/d70b85d64f26092bd2e040a44977687d806d2f59/espnet_onnx/export/asr/models/encoders/contextual_block_xformer.py#L180)
If you don't mind, would you fix this and create a PR?
