### ISSUE TITLE
max_seq_length not working for fastspeech2

### ISSUE THREAD

**Issue by sciai-ai** [espnet/espnet_onnx#59]
@Masao-Someki I tried changing the max_seq_length for fastspeech2, but it  gives error 

<img width="910" alt="image" src="https://user-images.githubusercontent.com/52277510/198968158-c479d300-2f1e-432c-8f93-d826e0b805b5.png">

I used the command while exporting and only changed the tag name

```m = TTSModelExport()
m.set_export_config(
    max_seq_len=3000
)
```

If i use the command with vits, it works well. Can you please check

**Comment by Masao-Someki** [comment]
@sciai-ai 
Thank you, I did't realize that we still have hard-coded script for MakePadMask..
We just need to fix [here](https://github.com/espnet/espnet_onnx/blob/d70b85d64f26092bd2e040a44977687d806d2f59/espnet_onnx/export/tts/models/tts_models/fastspeech2.py#L26) and everything would work for fastspeech2.
I found similar problem in tacotron2, so we need to fix that as well

**Comment by sciai-ai** [comment]
Still get an error after modfying the code

<img width="915" alt="image" src="https://user-images.githubusercontent.com/52277510/201028895-0946e0c3-8026-4cb0-9a9c-2419222a16f4.png">

<img width="912" alt="image" src="https://user-images.githubusercontent.com/52277510/201028997-58e50320-768f-4e01-8fba-943003b890b4.png">
