### ISSUE TITLE
For streaming model result first word is often missing when displaying the best hypo

### ISSUE THREAD

**Issue by espnetUser** [espnet/espnet_onnx#74]
Hi @Masao-Someki,

I am testing my streaming Conformer-Transformer model after converting it from espnet2 to onnx format. I noticed that the first word in the best hypo is often missing although it got recognized correctly (debug log is showing it via ("batch_beam_search:271) DEBUG: best hypo: ..." message).

I found some suspicious code in this line https://github.com/espnet/espnet_onnx/blob/master/espnet_onnx/asr/asr_streaming.py#164 where the  _get_result() function always removes the first two tokens:

```
def _get_result(self, hyp: Hypothesis):
        token_int = hyp.yseq[2:-1].astype(np.int64).tolist()
```

I think _get_result() should just remove the first & last token (assumed to be "<sos/eos>") like so:
```
def _get_result(self, hyp: Hypothesis):
        token_int = hyp.yseq[1:-1].astype(np.int64).tolist()
```
After the change my issue with missing word at beginning was resolved. So, this looks like a bug to me. 

Could you please double-check and let me know if I should create a PR?

Thanks!

**Comment by Masao-Someki** [comment]
Hi @espnetUser, 
thank you, this is a bug...
We need to fix this, so would you create a PR for this?
