### ISSUE TITLE
onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 211 by 421

### ISSUE THREAD

**Issue by QMZ321** [espnet/espnet_onnx#88]
**when I try to use inference demo, I got an error**
import librosa
from espnet_onnx import Speech2Text

speech2text = Speech2Text(model_dir='/root/autodl-tmp/.cache/espnet_onnx/librispeech_100-asr-conformer-aed')

wav_file = '../wav_test/121-121726-0000.wav'
y, sr = librosa.load(wav_file, sr=16000)
nbest = speech2text(y)

**error info**
/root/miniconda3/envs/espnet-onnx/lib/python3.8/site-packages/espnet_onnx/utils/abs_model.py:63: UserWarning: Inference will be executed on the CPU. Please provide gpu providers. Read `How to use GPU on espnet_onnx` in readme in detail.
  warnings.warn(
2023-04-15 19:34:26.289677552 [E:onnxruntime:, sequential_executor.cc:368 Execute] Non-zero status code returned while running Add node. Name:'Add_398' Status Message: /hdd/doc/onnxruntime/onnxruntime/core/providers/cpu/math/element_wise_ops.h:523 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 211 by 421

Traceback (most recent call last):
  File "inference.py", line 9, in <module>
    nbest = speech2text(y)
  File "/root/miniconda3/envs/espnet-onnx/lib/python3.8/site-packages/espnet_onnx/asr/asr_model.py", line 79, in __call__
    enc, _ = self.encoder(speech=speech, speech_length=lengths)
  File "/root/miniconda3/envs/espnet-onnx/lib/python3.8/site-packages/espnet_onnx/asr/model/encoders/encoder.py", line 70, in __call__
    self.forward_encoder(feats, feat_length)
  File "/root/miniconda3/envs/espnet-onnx/lib/python3.8/site-packages/espnet_onnx/asr/model/encoders/encoder.py", line 87, in forward_encoder
    self.encoder.run(["encoder_out", "encoder_out_lens"], {
  File "/root/miniconda3/envs/espnet-onnx/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'Add_398' Status Message: /hdd/doc/onnxruntime/onnxruntime/core/providers/cpu/math/element_wise_ops.h:523 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 211 by 421

**please help me. thank you very much!**

**Comment by QMZ321** [comment]
I found that it was not the problem of wav file loading, because when I switched to the timit dataset in the demo, for the same wav file, timit could work normally.

I guess there is a problem with the export of librispeech's conformer model, please help me！

**Comment by QMZ321** [comment]
After trying to load 'kamo-naoyuki/timit_asr_train_asr_raw_word_valid.acc.ave' and 'kamo-naoyuki/librispeech_asr_train_asr_conformer5_raw_bpe5000_frontend_confn_fft400_frontend_confhop_length160_scheduler_confwarmup_steps25000_batch_bins14000 After 0000_optim_conflr0.0015_initnone_sp_valid.acc.ave' **from espnet_model_zoo** , I guessed the problem was with **espnet-onnx export or export_from_zip**, because when I trained with **from_pretrained**, That's not going to happen

**Comment by QMZ321** [comment]
After trying to load 'kamo-naoyuki/timit_asr_train_asr_raw_word_valid.acc.ave' and 'kamo-naoyuki/librispeech_asr_train_asr_conformer5_raw_bpe5000_frontend_confn_fft400_frontend_confhop_length160_scheduler_confwarmup_steps25000_batch_bins14000 After 0000_optim_conflr0.0015_initnone_sp_valid.acc.ave' from **espnet_model_zoo** , I guessed the problem was with **espnet-onnx export or export_from_zip**, because when I ues **from_pretrained**, That's not going to happen

**Comment by Masao-Someki** [comment]
Hi @QMZ321, thank you for reporting your issue.
Am I right that you could successfully export the model `kamo-naoyuki/timit_asr_train_asr_...` with `export_from_pretrained` method? Basically, `export_from_pretrained` and `export_from_zip` do the same process, so I don't think we have an issue with `export_from_zip` if `export_from_pretrained` works.
The issue happens with the `Add_398` node, so it might be an issue with positional encoding. If possible, would you install `netron` and visualize the model structure around `Add_398` for further debugging? We need to figure out exactly what operation is causing this problem.(You can use `Ctrl + F` to search the node in netron)

**Comment by QMZ321** [comment]
Hi @Masao-Someki, thank you for your reply!
This is the result of the `netron` visualization. 
![image](https://user-images.githubusercontent.com/65494749/232264917-1d9533b2-fd73-4cae-a455-a9b50b1efd19.png)

**Comment by Masao-Someki** [comment]
Okay, it seems that the sequence length is difference in the following part. I think the sequence length of `matrix_ac` is 211 while `matrix_bd` is 421.
Would you check your rel_shift version? It seems that the model uses the `latest` version of relative position embedding while `legacy_rel_shift` is used during attention calculation.

https://github.com/espnet/espnet_onnx/blob/c074393d5536c51eb2c43d04de5a95eb8bc93e2b/espnet_onnx/export/asr/models/multihead_att.py#L86-L96

**Comment by QMZ321** [comment]
Sorry, I'm a newbie and don't know how to check the `rel_shift version`. This is the `config` I used during espnet training, I don't know if it can help.

This is the `config` I used
[https://github.com/espnet/espnet/blob/master/egs2/librispeech_100/asr1/conf/tuning/train_asr_conformer_lr2e-3_warmup15k_amp_nondeterministic.yaml](url)

is this one？
![image](https://user-images.githubusercontent.com/65494749/232273026-838ceeed-58a5-41f8-b698-99e166c9227b.png)

**Comment by Masao-Someki** [comment]
@QMZ321 
It seems that the configuration is correct. Just for clarification, which version of PyTorch, onnx, onnxruntime and espnet_onnx do you use?
If you installed espnet_onnx via pip, then would you clone this repository and check if the issue still happens with the latest script?

**Comment by QMZ321** [comment]
> It seems that the configuration is correct. Just for clarification, which version of PyTorch, onnx, onnxruntime and espnet_onnx do you use?

my version is: `pytorch=1.13.1`, `onnx=1.11.0`, `onnxruntime=1.11.1.espnet`, `espnet_onnx=0.1.10`



> If you installed espnet_onnx via pip, then would you clone this repository and check if the issue still happens with the latest script?

What are the steps to clone this repository? thank you!

**Comment by Masao-Someki** [comment]
@QMZ321 
Would you check the type of class for position embedding and multihead attention?
In that configuration, the position embedding should be the `RelPositionalEncoding` class, and attention should be the `RelPositionMultiHeadedAttention` class.
I think this issue happens with the `LegacyRelPositionMultiHeadedAttention` class.

**Comment by QMZ321** [comment]
For debug, I extracted the train part separately:
![image](https://user-images.githubusercontent.com/65494749/232860044-70379ec0-ec55-4751-95da-b8accf073926.png)
I inserted a breakpoint to see the type of rel_pos_type:
![image](https://user-images.githubusercontent.com/65494749/232857560-6c17395a-c384-4a11-8f51-5719f4c7a94f.png)
The result is as follows:
![de7da4e8c198cdb8bc4b60c234ddf58](https://user-images.githubusercontent.com/65494749/232857639-ed2ebf19-711f-4213-a622-4942f6908632.png)

**Comment by QMZ321** [comment]
@Masao-Someki 
I found that as long as the `optimize option` is disabled, 
```
from espnet_onnx.export import ASRModelExport

m = ASRModelExport()
# m = ASRModelExport('/root/autodl-tmp/.cache/espnet_onnx')
m.export_from_zip(
  '/root/autodl-tmp/projects/espnet_onnx_project/model/espnet/asr_train_asr_conformer_lr2e-3_warmup15k_amp_nondeterministic_raw_en_bpe5000_sp_valid.acc.ave.zip',
  tag_name='librispeech_100-asr-conformer-aed',
  quantize=True,
  # optimize=True
)
```
it works fine.
![image](https://user-images.githubusercontent.com/65494749/232995999-ae4add62-3405-46fc-931b-8166a93abb0b.png)
But I think the optimize option is very necessary for me, please help me.

**Comment by QMZ321** [comment]
@Masao-Someki 
Maybe it's a problem with `custom onnxruntime`? Because the `optimize option` is related to `custom onnxruntime`.
And I'm not sure if my `custom onnxruntime` is correct, because the link below `here` doesn't work.
![image](https://user-images.githubusercontent.com/65494749/233001392-e690b46f-ee24-4672-aac7-9a1abcb3474c.png)
instead I used the `latest` version of `custom onnxruntime` in `releases`
![image](https://user-images.githubusercontent.com/65494749/233002172-7ea60d74-d5b2-443b-9fae-d4dd64261ad9.png)

**Comment by QMZ321** [comment]
Thank you for your reply!
Through your method, I successfully solved the problem! 
Thank you very much!  
👍 👍 👍 :)
